---
title: "Stat 513"
image: ""
about:
  template: solana
---


## Instructor Information


|    Name | Role | Email | Office | Office Hours |
|---------|:-----|:------|:-------------|:-----------|
|   Sam Baugh | Instructor | samuelbaugh@psu.edu | Thomas 413 | MW 10:00-11:00 
|   Siyu Huang | TA | sph6006@psu.edu | Third floor lounge | F 12:00-13:00 


## Assignments

| Assignment | Due (11:59pm)  |  Solutions |
|:------------|:-----|:-----------|
| [Problem Set 1](files/classes/513F25/problem_sets/problem_set1.pdf) | September 7 | [Solutions](files/classes/513F25/problem_sets/problem_set1_solutions.pdf)|
| [Problem Set 2](files/classes/513F25/problem_sets/problem_set2.pdf) | September 21 | [Solutions](files/classes/513F25/problem_sets/problem_set2_solutions.pdf)|
| [Problem Set 3](files/classes/513F25/problem_sets/problem_set3.pdf) | October 5    | [Solutions](files/classes/513F25/problem_sets/problem_set3_solutions.pdf)|
| [Problem Set 4](files/classes/513F25/problem_sets/problem_set4.pdf) | October 19   | [Solutions](files/classes/513F25/problem_sets/problem_set4_solutions.pdf)|
| [Problem Set 5](files/classes/513F25/problem_sets/problem_set5.pdf) | November 12  | |

